name: Preview Environment

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build-and-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'yarn'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.5 # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
        if: github.event.action != 'closed' # You might want to skip the build if the PR has been closed
      - run: yarn install
      - run: yarn run build
      - run: bundle exec jekyll build --config _config.yml,jekyll-configs/dev.yml

      - name: Upload to artifact
        uses: actions/upload-artifact@v3
        with:
          name: preview-site
          path: ./_site  # Replace with the output directory of your build
