name: Preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  call-workflow-jekyll-build:
    uses: ./.github/workflows/jekyll-build.yml
    with: 
      jekyll-build-args: "bundle exec jekyll build --config _config.yml,jekyll-configs/dev.yml"
      github-sha: ${{ github.sha }}
      github-run-id: ${{ github.run_id }}
      github-event-number: ${{ github.event.number }}
      environment: "Preview"
      environment-url: "https://dev-design.va.gov/${{ github.event.number }}"
      s3-site: "s3://dev-design.va.gov/${{ github.event.number }}"
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
